### Importing Python Libraries

In [1]:
import os
from pathlib import Path
import numpy as np
import pandas as pd

### Setting the Dataset Folder Path

In [2]:
dataset_folder = Path("processed_eeg_dataset/")
print("Dataset folder:", dataset_folder)

Dataset folder: processed_eeg_dataset

### Defining File Paths

In [3]:
epoch_df_path = dataset_folder / "eeg_epoch_dataframe.pkl"
metadata_csv_path = dataset_folder / "eeg_metadata.csv"
groups_path = dataset_folder / "groups.npy"
x_eeg_path = dataset_folder / "X_eeg.npy"
x_images_path = dataset_folder / "X_images.npy"
y_labels_path = dataset_folder / "y_labels.npy"

### Checking Whether All Files Exist

In [4]:
files_dict = {
    "eeg_epoch_dataframe.pkl": epoch_df_path,
    "eeg_metadata.csv": metadata_csv_path,
    "groups.npy": groups_path,
    "X_eeg.npy": x_eeg_path,
    "X_images.npy": x_images_path,
    "y_labels.npy": y_labels_path
}

for file_name, file_path in files_dict.items():
    print(f"{file_name}: {'Found' if file_path.exists() else 'Missing'}")

eeg_epoch_dataframe.pkl: Found
eeg_metadata.csv: Found
groups.npy: Found
X_eeg.npy: Found
X_images.npy: Found
y_labels.npy: Found

### Loading `eeg_epoch_dataframe.pkl`

In [5]:
eeg_epoch_df = pd.read_pickle(epoch_df_path)
print("eeg_epoch_dataframe loaded successfully")

eeg_epoch_dataframe loaded successfully

### Viewing the Basic Information of `eeg_epoch_dataframe`

In [6]:
print("Shape:", eeg_epoch_df.shape)
print("\nColumns:")
print(eeg_epoch_df.columns.tolist())

Shape: (8300, 16)

Columns:
['subject_id', 'session', 'task', 'label', 'label_name', 'epoch_index', 'sfreq', 'n_channels', 'n_times', 'img_channels', 'img_height', 'img_width', 'channel_names', 'file_path', 'eeg_epoch', 'image_tensor']

### Preview Basic Information of `eeg_epoch_dataframe`

In [7]:
eeg_epoch_df.head()

,subject_id,session,task,label,label_name,epoch_index,sfreq,n_channels,n_times,img_channels,img_height,img_width,channel_names,file_path,eeg_epoch,image_tensor
0,sub-01,ses-1,eyesopen,0,NS,0,250.0,61,1250,3,61,1250,"[Fp1, AF3, AF7, Fz, F1, F3, F5, F7, FC1, FC3, ...",data\sub-01\ses-1\eeg\sub-01_ses-1_task-eyesop...,"[[0.06909623, 0.010095196, -0.230486, -0.65709...","[[[78, 77, 72, 63, 55, 51, 53, 59, 63, 63, 60,..."
1,sub-01,ses-1,eyesopen,0,NS,1,250.0,61,1250,3,61,1250,"[Fp1, AF3, AF7, Fz, F1, F3, F5, F7, FC1, FC3, ...",data\sub-01\ses-1\eeg\sub-01_ses-1_task-eyesop...,"[[-1.139759, -1.0737023, -0.9242942, -0.680545...","[[[85, 87, 92, 99, 106, 108, 105, 100, 96, 94,..."
2,sub-01,ses-1,eyesopen,0,NS,2,250.0,61,1250,3,61,1250,"[Fp1, AF3, AF7, Fz, F1, F3, F5, F7, FC1, FC3, ...",data\sub-01\ses-1\eeg\sub-01_ses-1_task-eyesop...,"[[0.00058771274, 0.098988324, 0.22626135, 0.33...","[[[121, 124, 127, 130, 133, 137, 143, 149, 153..."
3,sub-01,ses-1,eyesopen,0,NS,3,250.0,61,1250,3,61,1250,"[Fp1, AF3, AF7, Fz, F1, F3, F5, F7, FC1, FC3, ...",data\sub-01\ses-1\eeg\sub-01_ses-1_task-eyesop...,"[[-0.4310731, -0.72415334, -0.8707683, -0.8094...","[[[116, 108, 103, 105, 112, 120, 126, 126, 121..."
4,sub-01,ses-1,eyesopen,0,NS,4,250.0,61,1250,3,61,1250,"[Fp1, AF3, AF7, Fz, F1, F3, F5, F7, FC1, FC3, ...",data\sub-01\ses-1\eeg\sub-01_ses-1_task-eyesop...,"[[-0.2380477, -0.24178983, -0.2522841, -0.2519...","[[[116, 116, 116, 116, 117, 118, 119, 119, 118..."

### Checking Data Types of `eeg_epoch_dataframe`

In [8]:
eeg_epoch_df.dtypes

subject_id           str
session              str
task                 str
label              int64
label_name           str
epoch_index        int64
sfreq            float64
n_channels         int64
n_times            int64
img_channels       int64
img_height         int64
img_width          int64
channel_names     object
file_path            str
eeg_epoch         object
image_tensor      object
dtype: object

### Check missing values in `eeg_epoch_dataframe`

In [9]:
eeg_epoch_df.isnull().sum()

subject_id       0
session          0
task             0
label            0
label_name       0
epoch_index      0
sfreq            0
n_channels       0
n_times          0
img_channels     0
img_height       0
img_width        0
channel_names    0
file_path        0
eeg_epoch        0
image_tensor     0
dtype: int64

### Load `eeg_metadata.csv`

In [10]:
eeg_metadata_df = pd.read_csv(metadata_csv_path)
print("eeg_metadata.csv loaded successfully")

eeg_metadata.csv loaded successfully

### View Basic Information of `eeg_metadata.csv`

In [11]:
print("Shape:", eeg_metadata_df.shape)
print("\nColumns:")
print(eeg_metadata_df.columns.tolist())

Shape: (8300, 13)

Columns:
['subject_id', 'session', 'task', 'label', 'label_name', 'epoch_index', 'sfreq', 'n_channels', 'n_times', 'img_channels', 'img_height', 'img_width', 'file_path']

### Previewing First 5 Rows of `eeg_metadata.csv`

In [12]:
eeg_metadata_df.head()

,subject_id,session,task,label,label_name,epoch_index,sfreq,n_channels,n_times,img_channels,img_height,img_width,file_path
0,sub-01,ses-1,eyesopen,0,NS,0,250.0,61,1250,3,61,1250,data\sub-01\ses-1\eeg\sub-01_ses-1_task-eyesop...
1,sub-01,ses-1,eyesopen,0,NS,1,250.0,61,1250,3,61,1250,data\sub-01\ses-1\eeg\sub-01_ses-1_task-eyesop...
2,sub-01,ses-1,eyesopen,0,NS,2,250.0,61,1250,3,61,1250,data\sub-01\ses-1\eeg\sub-01_ses-1_task-eyesop...
3,sub-01,ses-1,eyesopen,0,NS,3,250.0,61,1250,3,61,1250,data\sub-01\ses-1\eeg\sub-01_ses-1_task-eyesop...
4,sub-01,ses-1,eyesopen,0,NS,4,250.0,61,1250,3,61,1250,data\sub-01\ses-1\eeg\sub-01_ses-1_task-eyesop...

### Checking Data Types of `eeg_metadata.csv`

In [13]:
eeg_metadata_df.dtypes

subject_id          str
session             str
task                str
label             int64
label_name          str
epoch_index       int64
sfreq           float64
n_channels        int64
n_times           int64
img_channels      int64
img_height        int64
img_width         int64
file_path           str
dtype: object

### Loading `groups.npy`

In [14]:
groups = np.load(groups_path, allow_pickle=True)
print("groups.npy loaded successfully")

groups.npy loaded successfully

### Inspecting `groups.npy`

In [15]:
print("Shape:", groups.shape)
print("Data type:", groups.dtype)
print("First 10 values:", groups[:10])

Shape: (8300,)
Data type: object
First 10 values: ['sub-01' 'sub-01' 'sub-01' 'sub-01' 'sub-01' 'sub-01' 'sub-01' 'sub-01'
 'sub-01' 'sub-01']

### Unique Groups and Counts

In [16]:
unique_groups, group_counts = np.unique(groups, return_counts=True)

print("Number of unique groups:", len(unique_groups))
print("\nFirst few unique groups with counts:")
for g, c in zip(unique_groups[:10], group_counts[:10]):
    print(g, "->", c)

Number of unique groups: 71

First few unique groups with counts:
sub-01 -> 60
sub-02 -> 120
sub-03 -> 120
sub-04 -> 120
sub-05 -> 120
sub-06 -> 120
sub-07 -> 120
sub-08 -> 120
sub-09 -> 120
sub-10 -> 120

### Loading `X_eeg.npy`

In [17]:
X_eeg = np.load(x_eeg_path, allow_pickle=True)
print("X_eeg.npy loaded successfully")

X_eeg.npy loaded successfully

### Inspecting `X_eeg.npy`

In [18]:
print("Shape:", X_eeg.shape)
print("Data type:", X_eeg.dtype)

Shape: (8300, 61, 1250)
Data type: float32

### Viewing One EEG Sample

In [19]:
print("First sample shape:", X_eeg[0].shape)
print(X_eeg[0])

First sample shape: (61, 1250)
[[ 0.06909623  0.0100952  -0.230486   ... -1.6944001  -1.5014523
  -1.3084279 ]
 [ 0.04237435 -0.18452397 -0.48758063 ... -1.6319453  -1.4080198
  -1.4443766 ]
 [ 0.08175743 -0.20022608 -0.56045216 ... -1.0344888  -0.8949572
  -0.6040857 ]
 ...
 [-0.01438453  0.71625304  1.396602   ... -0.4801522  -0.6883603
  -0.5909906 ]
 [-0.03518246  0.8014288   1.7115178  ... -0.70904845 -0.74759996
  -0.79897803]
 [ 0.04363956  1.0837971   2.0466383  ...  0.9474892   0.8435979
   0.8730428 ]]

### Loading `X_images.npy`

In [20]:
X_images = np.load(x_images_path, allow_pickle=True)
print("X_images.npy loaded successfully")

X_images.npy loaded successfully

### Inspecting `X_images.npy`

In [21]:
print("Shape:", X_images.shape)
print("Data type:", X_images.dtype)

Shape: (8300, 3, 61, 1250)
Data type: uint8

### Viewing One Image Sample

In [22]:
print("First image sample shape:", X_images[0].shape)
print(X_images[0])

First image sample shape: (3, 61, 1250)
[[[ 78  77  72 ...  42  46  50]
  [ 78  73  67 ...  43  48  47]
  [ 78  73  65 ...  56  58  64]
  ...
  [ 76  91 105 ...  67  63  65]
  [ 76  93 112 ...  62  61  60]
  [ 78  99 118 ...  96  94  95]]

 [[ 78  77  72 ...  42  46  50]
  [ 78  73  67 ...  43  48  47]
  [ 78  73  65 ...  56  58  64]
  ...
  [ 76  91 105 ...  67  63  65]
  [ 76  93 112 ...  62  61  60]
  [ 78  99 118 ...  96  94  95]]

 [[ 78  77  72 ...  42  46  50]
  [ 78  73  67 ...  43  48  47]
  [ 78  73  65 ...  56  58  64]
  ...
  [ 76  91 105 ...  67  63  65]
  [ 76  93 112 ...  62  61  60]
  [ 78  99 118 ...  96  94  95]]]

### Loading `y_labels.npy`

In [23]:
y_labels = np.load(y_labels_path, allow_pickle=True)
print("y_labels.npy loaded successfully")

y_labels.npy loaded successfully

### Inspecting `y_labels.npy`

In [24]:
print("Shape:", y_labels.shape)
print("Data type:", y_labels.dtype)
print("First 20 labels:", y_labels[:20])

Shape: (8300,)
Data type: int64
First 20 labels: [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]

### Checking the Label Distribution

In [25]:
unique_labels, label_counts = np.unique(y_labels, return_counts=True)

print("Label distribution:")
for label, count in zip(unique_labels, label_counts):
    print(label, "->", count)

Label distribution:
0 -> 4249
1 -> 4051

### Comparing Sample Counts Across All Loaded Files

In [26]:
print("Number of samples in eeg_epoch_dataframe:", len(eeg_epoch_df))
print("Number of samples in eeg_metadata.csv:", len(eeg_metadata_df))
print("Number of samples in groups.npy:", len(groups))
print("Number of samples in X_eeg.npy:", len(X_eeg))
print("Number of samples in X_images.npy:", len(X_images))
print("Number of samples in y_labels.npy:", len(y_labels))

Number of samples in eeg_epoch_dataframe: 8300
Number of samples in eeg_metadata.csv: 8300
Number of samples in groups.npy: 8300
Number of samples in X_eeg.npy: 8300
Number of samples in X_images.npy: 8300
Number of samples in y_labels.npy: 8300

### Checking Whether All Sample Counts Match

In [27]:
sample_counts = {
    "eeg_epoch_dataframe": len(eeg_epoch_df),
    "eeg_metadata": len(eeg_metadata_df),
    "groups": len(groups),
    "X_eeg": len(X_eeg),
    "X_images": len(X_images),
    "y_labels": len(y_labels)
}

all_same = len(set(sample_counts.values())) == 1

print("Do all files have the same number of samples?", all_same)
print("\nSample counts:")
print(sample_counts)

Do all files have the same number of samples? True

Sample counts:
{'eeg_epoch_dataframe': 8300, 'eeg_metadata': 8300, 'groups': 8300, 'X_eeg': 8300, 'X_images': 8300, 'y_labels': 8300}

### Creating a Simple Summary Table

In [28]:
summary_df = pd.DataFrame({
    "File": ["eeg_epoch_dataframe.pkl", "eeg_metadata.csv", "groups.npy", "X_eeg.npy", "X_images.npy", "y_labels.npy"],
    "Loaded": [True, True, True, True, True, True],
    "Samples": [len(eeg_epoch_df), len(eeg_metadata_df), len(groups), len(X_eeg), len(X_images), len(y_labels)]
})

summary_df

                      File  Loaded  Samples
0  eeg_epoch_dataframe.pkl    True     8300
1         eeg_metadata.csv    True     8300
2               groups.npy    True     8300
3                X_eeg.npy    True     8300
4             X_images.npy    True     8300
5             y_labels.npy    True     8300

### Checking the First Sample Alignment Across Files

In [29]:
print("Sample 0 label:", y_labels[0])
print("Sample 0 group:", groups[0])

print("\nSample 0 metadata row from eeg_metadata.csv:")
print(eeg_metadata_df.iloc[0])

print("\nSample 0 row from eeg_epoch_dataframe:")
print(eeg_epoch_df.iloc[0])

Sample 0 label: 0
Sample 0 group: sub-01

Sample 0 metadata row from eeg_metadata.csv:
subject_id                                                 sub-01
session                                                     ses-1
task                                                     eyesopen
label                                                           0
label_name                                                     NS
epoch_index                                                     0
sfreq                                                       250.0
n_channels                                                     61
n_times                                                      1250
img_channels                                                    3
img_height                                                     61
img_width                                                    1250
file_path       data\sub-01\ses-1\eeg\sub-01_ses-1_task-eyesop...
Name: 0, dtype: object

Sample 0 row from eeg_epoch_dataframe:
subject_id                                                  sub-01
session                                                      ses-1
task                                                      eyesopen
label                                                            0
label_name                                                      NS
epoch_index                                                      0
sfreq                                                        250.0
n_channels                                                      61
n_times                                                       1250
img_channels                                                     3
img_height                                                      61
img_width                                                     1250
channel_names    [Fp1, AF3, AF7, Fz, F1, F3, F5, F7, FC1, FC3, ...
file_path        data\sub-01\ses-1\eeg\sub-01_ses-1_task-eyesop...
eeg_epoch        [[0.06909623, 0.010095196, -0.230486, -0.65709...
image_tensor     [[[78, 77, 72, 63, 55, 51, 53, 59, 63, 63, 60,...
Name: 0, dtype: object

### Inspecting EEG Tensor Dimensions More Clearly

In [30]:
print("X_eeg full shape:", X_eeg.shape)

if len(X_eeg.shape) == 3:
    print("Possible interpretation:")
    print("Number of samples   :", X_eeg.shape[0])
    print("Dimension 1         :", X_eeg.shape[1])
    print("Dimension 2         :", X_eeg.shape[2])

elif len(X_eeg.shape) == 4:
    print("Possible interpretation:")
    print("Number of samples   :", X_eeg.shape[0])
    print("Dimension 1         :", X_eeg.shape[1])
    print("Dimension 2         :", X_eeg.shape[2])
    print("Dimension 3         :", X_eeg.shape[3])

X_eeg full shape: (8300, 61, 1250)
Possible interpretation:
Number of samples   : 8300
Dimension 1         : 61
Dimension 2         : 1250

### Inspecting Image Tensor Dimensions More Clearly

In [31]:
print("X_images full shape:", X_images.shape)

if len(X_images.shape) == 3:
    print("Possible interpretation:")
    print("Number of samples:", X_images.shape[0])
    print("Height           :", X_images.shape[1])
    print("Width            :", X_images.shape[2])

elif len(X_images.shape) == 4:
    print("Possible interpretation:")
    print("Number of samples:", X_images.shape[0])
    print("Height           :", X_images.shape[1])
    print("Width            :", X_images.shape[2])
    print("Channels         :", X_images.shape[3])

X_images full shape: (8300, 3, 61, 1250)
Possible interpretation:
Number of samples: 8300
Height           : 3
Width            : 61
Channels         : 1250

### Creating One Combined Review Dictionary

In [32]:
dataset_review = {
    "eeg_epoch_dataframe_shape": eeg_epoch_df.shape,
    "eeg_metadata_shape": eeg_metadata_df.shape,
    "groups_shape": groups.shape,
    "X_eeg_shape": X_eeg.shape,
    "X_images_shape": X_images.shape,
    "y_labels_shape": y_labels.shape,
    "unique_labels": np.unique(y_labels).tolist(),
    "number_of_groups": len(np.unique(groups))
}

dataset_review

{'eeg_epoch_dataframe_shape': (8300, 16),
 'eeg_metadata_shape': (8300, 13),
 'groups_shape': (8300,),
 'X_eeg_shape': (8300, 61, 1250),
 'X_images_shape': (8300, 3, 61, 1250),
 'y_labels_shape': (8300,),
 'unique_labels': [0, 1],
 'number_of_groups': 71}

### Final Review Print

In [33]:
print("DATASET REVIEW COMPLETE")
print("-" * 40)
print("eeg_epoch_dataframe shape:", eeg_epoch_df.shape)
print("eeg_metadata shape      :", eeg_metadata_df.shape)
print("groups shape            :", groups.shape)
print("X_eeg shape             :", X_eeg.shape)
print("X_images shape          :", X_images.shape)
print("y_labels shape          :", y_labels.shape)
print("Unique labels           :", np.unique(y_labels))
print("Number of unique groups :", len(np.unique(groups)))

DATASET REVIEW COMPLETE
----------------------------------------
eeg_epoch_dataframe shape: (8300, 16)
eeg_metadata shape      : (8300, 13)
groups shape            : (8300,)
X_eeg shape             : (8300, 61, 1250)
X_images shape          : (8300, 3, 61, 1250)
y_labels shape          : (8300,)
Unique labels           : [0 1]
Number of unique groups : 71